{
 "title": "Lab8",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Add Student Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(hello_addstudent_count_total{})"
    }
   ]
  },
  {
   "title": "Add Student Grade Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(hello_addstudentgrades_time_seconds_sum[5m])) / sum(rate(hello_addstudentgrades_time_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Get Student Grades Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(hello_studentgrades_time_seconds_sum[5m])) / sum(rate(hello_studentgrades_time_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Update Teacher Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(hello_updateteacher_time_seconds_count{})"
    }
   ]
  }
 ]
}